# Generated by Django 5.1.4 on 2024-12-11 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_project_end_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_members',
            field=models.ManyToManyField(blank=True, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
