# Generated by Django 5.1.4 on 2024-12-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_task_options_task_priority_alter_task_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
