# Generated by Django 5.1.4 on 2024-12-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=15),
        ),
    ]
