# Generated by Django 5.1.4 on 2024-12-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0025_task_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
