# Generated by Django 5.1.4 on 2024-12-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0035_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
