# Generated by Django 5.1.4 on 2024-12-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0037_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
