# Generated by Django 5.1.4 on 2024-12-31 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0040_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
